SET IDENTITY_INSERT [dbo].[Courts] ON

INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (001,N'Върховен административен съд',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (002,N'Върховен касационен съд',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (100,N'Апелативен съд - София',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (101,N'Апелативен специализиран наказателен съд',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (105,N'Специализиран наказателен съд',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (110,N'Софийски градски съд',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (111,N'Софийски районен съд',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (120,N'Окръжен съд - Благоевград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (121,N'Районен съд - Благоевград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (122,N'Районен съд - Гоце Делчев',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (123,N'Районен съд - Петрич',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (124,N'Районен съд - Разлог',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (125,N'Районен съд - Сандански',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (130,N'Окръжен съд - Видин',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (131,N'Районен съд - Белоградчик',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (132,N'Районен съд - Видин',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (133,N'Районен съд - Кула',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (140,N'Окръжен съд - Враца',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (141,N'Районен съд - Бяла Слатина',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (142,N'Районен съд - Враца',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (144,N'Районен съд - Козлодуй',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (145,N'Районен съд - Мездра',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (146,N'Районен съд - Оряхово',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (150,N'Окръжен съд - Кюстендил',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (151,N'Районен съд - Дупница',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (152,N'Районен съд - Кюстендил',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (160,N'Окръжен съд - Монтана',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (161,N'Районен съд - Берковица',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (162,N'Районен съд - Лом',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (163,N'Районен съд - Монтана',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (170,N'Окръжен съд - Перник',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (171,N'Районен съд - Брезник',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (172,N'Районен съд - Перник',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (173,N'Районен съд - Радомир',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (174,N'Районен съд - Трън',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (180,N'Софийски окръжен съд',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (181,N'Районен съд - Ботевград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (182,N'Районен съд - Елин Пелин',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (183,N'Районен съд - Етрополе',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (184,N'Районен съд - Ихтиман',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (185,N'Районен съд - Костинброд',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (186,N'Районен съд - Пирдоп',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (187,N'Районен съд - Самоков',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (188,N'Районен съд - Своге',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (189,N'Районен съд - Сливница',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (200,N'Апелативен съд - Бургас',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (210,N'Окръжен съд - Бургас',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (211,N'Районен съд - Айтос',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (212,N'Районен съд - Бургас',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (213,N'Районен съд - Карнобат',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (214,N'Районен съд - Малко Търново',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (215,N'Районен съд - Несебър',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (216,N'Районен съд - Поморие',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (217,N'Районен съд - Средец',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (218,N'Районен съд - Царево',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (220,N'Окръжен съд - Сливен',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (221,N'Районен съд - Котел',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (222,N'Районен съд - Нова Загора',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (223,N'Районен съд - Сливен',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (230,N'Окръжен съд - Ямбол',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (231,N'Районен съд - Елхово',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (232,N'Районен съд - Тополовград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (233,N'Районен съд - Ямбол',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (300,N'Апелативен съд - Варна',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (310,N'Окръжен съд - Варна',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (311,N'Районен съд - Варна',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (312,N'Районен съд - Девня',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (313,N'Районен съд - Провадия',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (320,N'Окръжен съд - Добрич',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (321,N'Районен съд - Балчик',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (322,N'Районен съд - Ген. Тошево',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (323,N'Районен съд - Добрич',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (324,N'Районен съд - Каварна',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (325,N'Районен съд - Тервел',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (330,N'Окръжен съд - Разград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (331,N'Районен съд - Исперих',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (332,N'Районен съд - Кубрат',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (333,N'Районен съд - Разград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (340,N'Окръжен съд - Силистра',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (341,N'Районен съд - Дулово',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (342,N'Районен съд - Силистра',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (343,N'Районен съд - Тутракан',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (350,N'Окръжен съд - Търговище',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (351,N'Районен съд - Омуртаг',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (352,N'Районен съд - Попово',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (353,N'Районен съд - Търговище',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (360,N'Окръжен съд - Шумен',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (361,N'Районен съд - Велики Преслав',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (362,N'Районен съд - Нови пазар',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (363,N'Районен съд - Шумен',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (400,N'Апелативен съд - Велико Търново',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (410,N'Окръжен съд - Велико Търново',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (411,N'Районен съд - Велико Търново',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (412,N'Районен съд - Горна Оряховица',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (413,N'Районен съд - Елена',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (414,N'Районен съд - Павликени',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (415,N'Районен съд - Свищов',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (420,N'Окръжен съд - Габрово',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (421,N'Районен съд - Габрово',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (422,N'Районен съд - Дряново',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (423,N'Районен съд - Севлиево',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (424,N'Районен съд - Трявна',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (430,N'Окръжен съд - Ловеч',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (431,N'Районен съд - Ловеч',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (432,N'Районен съд - Луковит',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (433,N'Районен съд - Тетевен',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (434,N'Районен съд - Троян',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (440,N'Окръжен съд - Плевен',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (441,N'Районен съд - Левски',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (442,N'Районен съд - Никопол',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (443,N'Районен съд - Плевен',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (444,N'Районен съд - Червен бряг',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (143,N'Районен съд - Кнежа',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (450,N'Окръжен съд - Русе',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (451,N'Районен съд - Бяла',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (452,N'Районен съд - Русе',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (500,N'Апелативен съд - Пловдив',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (510,N'Окръжен съд - Кърджали',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (511,N'Районен съд - Ардино',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (513,N'Районен съд - Крумовград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (514,N'Районен съд - Кърджали',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (515,N'Районен съд - Момчилград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (520,N'Окръжен съд - Пазарджик',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (521,N'Районен съд - Велинград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (522,N'Районен съд - Пазарджик',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (523,N'Районен съд - Панагюрище',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (524,N'Районен съд - Пещера',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (530,N'Окръжен съд - Пловдив',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (531,N'Районен съд - Асеновград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (532,N'Районен съд - Карлово',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (533,N'Районен съд - Пловдив',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (534,N'Районен съд - Първомай',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (540,N'Окръжен съд - Смолян',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (541,N'Районен съд - Девин',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (542,N'Районен съд - Златоград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (543,N'Районен съд - Мадан',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (544,N'Районен съд - Смолян',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (545,N'Районен съд - Чепеларе',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (550,N'Окръжен съд - Стара Загора',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (551,N'Районен съд - Казанлък',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (552,N'Районен съд - Раднево',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (553,N'Районен съд - Ст.Загора',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (554,N'Районен съд - Чирпан',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (555,N'Районен съд - Гълъбово',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (560,N'Окръжен съд - Хасково',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (561,N'Районен съд - Димитровград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (562,N'Районен съд - Свиленград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (563,N'Районен съд - Харманли',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (564,N'Районен съд - Хасково',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (565,N'Районен съд - Ивайловград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (600,N'Военно-апелативен съд',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (610,N'Военен съд - София',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (620,N'Военен съд - Пловдив',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (630,N'Военен съд - Варна',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (640,N'Военен съд - Плевен',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (650,N'Военен съд - Сливен',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (701,N'Административен съд - София-град',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (702,N'Административен съд - София-област',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (703,N'Административен съд - Благоевград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (704,N'Административен съд - Бургас',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (705,N'Административен съд - Варна',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (706,N'Административен съд - Велико Търново',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (707,N'Административен съд - Видин',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (708,N'Административен съд - Враца',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (709,N'Административен съд - Габрово',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (710,N'Административен съд - Добрич',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (711,N'Административен съд - Кюстендил',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (712,N'Административен съд - Кърджали',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (713,N'Административен съд - Ловеч',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (714,N'Административен съд - Монтана',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (715,N'Административен съд - Пазарджик',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (716,N'Административен съд - Перник',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (717,N'Административен съд - Плевен',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (718,N'Административен съд - Пловдив',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (719,N'Административен съд - Разград',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (720,N'Административен съд - Русе',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (721,N'Административен съд - Силистра',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (722,N'Административен съд - Сливен',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (723,N'Административен съд - Смолян',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (724,N'Административен съд - Стара Загора ',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (725,N'Административен съд - Търговище ',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (726,N'Административен съд - Хасково ',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (727,N'Административен съд - Шумен ',1);
INSERT INTO [dbo].[Courts] ([CourtId], [Name], [IsActive]) VALUES (728,N'Административен съд - Ямбол ',1);

SET IDENTITY_INSERT [dbo].[Courts] OFF
GO