SET IDENTITY_INSERT [dbo].[Involvements] ON

INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9001,N'Вносител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9002,N'Възложител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9003,N'Обвинител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9004,N'Ищец',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9005,N'Молител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9006,N'Заявител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9007,N'Жалбоподател',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9008,N'Жалбоподател-подсъдим',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9009,N'Жалбоподател-гр.ищец',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9010,N'Жалбоподател-ч.обвинител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9011,N'Жалбоподател-ответник',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9012,N'Протестираща страна',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9013,N'Въззивник',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9014,N'Тъжител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9015,N'Собственик',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9016,N'Кредитор',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9017,N'Съдружник',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9018,N'Управител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9019,N'Прокурист',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9020,N'Търговски представител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9021,N'Член на УС',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9022,N'Член на СД',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9023,N'Касатор',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9024,N'Пастор',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9025,N'Епископ',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9026,N'Ахриепископ',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9027,N'Пастир',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9028,N'Член на Духовен съвет',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9029,N'Председател',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9030,N'Член на Съвет на старейшините',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9031,N'Трето лице',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9032,N'Член на Епархийски съвет',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9033,N'Изпълнителен директор',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9034,N'Член на Брахмана съвет',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9035,N'Друго',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9036,N'Подсъдим',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9037,N'Ответник',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9038,N'Страна',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9039,N'Насрещна страна',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9040,N'Нарушител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9041,N'Уличено лице',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9042,N'Въззиваема страна',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9043,N'Наследодател',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9044,N'Админ.наказ.орган',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9045,N'Актосъставител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9046,N'Освидетелстван',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9047,N'Длъжник',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9048,N'Взискател',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9049,N'Обвиняем',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9050,N'Осъден',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9051,N'Лице по принудително действие',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9052,N'Страна',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9053,N'Трето лице помагач',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9054,N'Трето неучастващо лице',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9055,N'Главно встъпило лице',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9056,N'Контролираща страна',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9057,N'Заинтересована страна',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9058,N'Служебно конституирана страна',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9059,N'Необжалвал другар',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9060,N'Синдик',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9061,N'Помощник-синдик',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9062,N'Ликвидатор',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9063,N'Одитор',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9064,N'Пострадал',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9065,N'Страна по първоинст.дело',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9066,N'Граждански ищец',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9067,N'Частен обвинител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9068,N'Граждански ответник',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9069,N'Свидетел',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9070,N'Вещо лице',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9071,N'Експерт',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9072,N'Поемно лице',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9073,N'Родител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9074,N'Процесуален представител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9075,N'Защитник',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9076,N'Служебен защитник',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9077,N'Представител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9078,N'Законен представител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9079,N'Настойник',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9080,N'Попечител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9081,N'Особен представител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9082,N'Адвокат',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9083,N'Пълномощник',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9084,N'Представляващ',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9085,N'Повереник',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9086,N'Лице за съдебен адрес',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9087,N'Гр. ищец и ч. обвинител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9088,N'Жалбоподател - Осъдено лице',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9089,N'Искано лице',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9090,N'Комитет на кредиторите',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9091,N'Надзорен орган',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9092,N'Неограничено отговорен съдружник',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9093,N'Ощетено юридическо лице',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9094,N'Педагог',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9095,N'Преводач',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9096,N'Председател на ПС',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9097,N'Солидарен длъжник',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9098,N'Частен жалбоподател',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9099,N'Частен жалбоподател-длъжник',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9100,N'Частен жалбоподател-заявител',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9101,N'Частен жалбоподател',1);
INSERT INTO [dbo].[Involvements] ([InvolvementId], [Name], [IsActive]) VALUES (9102,N'Юрисконсулт',1);

SET IDENTITY_INSERT [dbo].[Involvements] OFF
GO