SET IDENTITY_INSERT [dbo].[ResultsOfAppeals] ON

INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (261,'1',N'Изцяло потвърдено',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (262,'2',N'Изцяло отменено, обезсилено или нищожно , върнато или не за ново разглеждане',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (263,'3',N'Изцяло отменено или обезсилено по обективни причини',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (264,'3а',N'Изцяло отменено или обезсилено по обективни причини:<br /> - поради  представяне на нови доказателства пред въззивната инстанция, които са обусловили отмяната или обезсилването',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (265,'3б',N'Изцяло отменено или обезсилено по обективни причини:<br /> - отказ или оттегляне пред въззивна (касационна) инстанция на исковата молба или постигане на спогодба пред въззивна (касационна) инстанция',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (266,'3в',N'Изцяло отменено или обезсилено по обективни причини:<br /> - поради заличаване от търговския регистър или приемане на вземането на ищеца, когато срещу ответника е открито производство по несъстоятелност и вземането на ищеца е прието',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (267,'3г',N'Изцяло отменено или обезсилено по обективни причини:<br /> - възражение за давност пред въззивната инстанция',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (268,'4',N'Потвърдено в една част отменено, обезсилено или нищожно, върнато или не за ново разглеждане в друга част',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (269,'5',N'Потвърдено в една част отменено или обезсилено в друга част по обективни причини',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (270,'5а',N'Потвърдено в една част отменено или обезсилено в друга част по обективни причини:<br /> - поради  представяне на нови доказателства пред въззивната инстанция, които са обусловили отмяната или обезсилването',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (271,'5б',N'Потвърдено в една част отменено или обезсилено в друга част по обективни причини:<br /> - отказ или оттегляне пред въззивна (касационна) инстанция на исковата молба или постигане на спогодба пред въззивна (касационна) инстанция',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (272,'5в',N'Потвърдено в една част отменено или обезсилено в друга част по обективни причини:<br /> - поради заличаване от търговския регистър или приемане на вземането на ищеца, когато срещу ответника е открито производство по несъстоятелност и вземането на ищеца е прието',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (273,'5г',N'Потвърдено в една част отменено или обезсилено в друга част по обективни причини:<br /> - възражение за давност пред въззивната инстанция',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (274,'6',N'Отменено, обезсилено или нищожно , върнато или не за ново разглеждане в друга част отменено или обезсилено в друга част по обективни причини',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (275,'6а',N'Отменено, обезсилено или нищожно , върнато или не за ново разглеждане в друга част отменено или обезсилено в друга част по обективни причини:<br /> - поради  представяне на нови доказателства пред въззивната инстанция, които са обусловили отмяната или обезсилването',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (276,'6б',N'Отменено, обезсилено или нищожно , върнато или не за ново разглеждане в друга част отменено или обезсилено в друга част по обективни причини:<br /> - отказ или оттегляне пред въззивна (касационна) инстанция на исковата молба или постигане на спогодба пред въззивна (касационна) инстанция',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (277,'6в',N'Отменено, обезсилено или нищожно , върнато или не за ново разглеждане в друга част отменено или обезсилено в друга част по обективни причини:<br /> - поради заличаване от търговския регистър или приемане на вземането на ищеца, когато срещу ответника е открито производство по несъстоятелност и вземането на ищеца е прието',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (278,'6г',N'Отменено, обезсилено или нищожно , върнато или не за ново разглеждане в друга част отменено или обезсилено в друга част по обективни причини:<br /> - възражение за давност пред въззивната инстанция',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (279,'7',N'Потвърдено в една част отменено, обезсилено или нищожно, върнато или не за ново разглеждане в друга част отменено или обезсилено в друга част по обективни причини',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (280,'7а',N'Потвърдено в една част отменено, обезсилено или нищожно, върнато или не за ново разглеждане в друга част отменено или обезсилено в друга част по обективни причини:<br /> - поради  представяне на нови доказателства пред въззивната инстанция, които са обусловили отмяната или обезсилването',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (281,'7б',N'Потвърдено в една част отменено, обезсилено или нищожно, върнато или не за ново разглеждане в друга част отменено или обезсилено в друга част по обективни причини:<br /> - отказ или оттегляне пред въззивна (касационна) инстанция на исковата молба или постигане на спогодба пред въззивна (касационна) инстанция',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (282,'7в',N'Потвърдено в една част отменено, обезсилено или нищожно, върнато или не за ново разглеждане в друга част отменено или обезсилено в друга част по обективни причини:<br /> - поради заличаване от търговския регистър или приемане на вземането на ищеца, когато срещу ответника е открито производство по несъстоятелност и вземането на ищеца е прието',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (283,'7г',N'Потвърдено в една част отменено, обезсилено или нищожно, върнато или не за ново разглеждане в друга част отменено или обезсилено в друга част по обективни причини:<br /> - възражение за давност пред въззивната инстанция',1);

INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (300,'1',N'Потвърден',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (301,'2',N'Отменен',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (302,'2а',N'Отменен и върнат за ново разглеждане на въззивния съд',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (303,'2б',N'Отменен и върнат за ново разглеждане на първоинстанционния съд',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (304,'2в',N'Отменен и върнат на прокурора',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (305,'3',N'Изменен',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (306,'3а',N'Изменен в наказателната част',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (307,'3б',N'Изменен в гражданско-осъдителната част',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (308,'2г',N'Отменен изцяло',1);

INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (400,'1',N'ОСТАВЕНО В СИЛА',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (401,'2',N'ОТМЕНЕНО изцяло, поради наличие на касационните основания по чл.209, т.3 АПК',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (402,'2а',N'ОБЕЗСИЛЕНО по чл.221, ал.3 АПК',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (403,'2б',N'ОБЯВЕНО ЗА НИЩОЖНО по чл.221, ал.5 АПК',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (404,'3',N'Частично отменено и обезсилено, поради наличие на касационните основания по чл.209, т.3 АПК',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (405,'4',N'ОТМЕНЕНО изцяло, на основание извън тези по чл.209, т.3 АПК',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (406,'4а-1',N'ОБЕЗСИЛЕНО, поради оттегляне на жалбата, респ. исковата молба',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (407,'4а-2',N'ОБЕЗСИЛЕНО, поради оттегляне на обжалвания административен акт по чл.221, ал.4 АПК',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (408,'4а-3',N'ОБЕЗСИЛЕНО, поради сключване на споразумение по чл.221, ал.6 АПК',1);
INSERT INTO [dbo].[ResultsOfAppeals] ([ResultsOfAppealId],[Code],[Description],[IsActive]) VALUES (409,'5',N'Частично отменено и обезсилено, на основание извън тези по чл.209, т.3 АПК',1);
																																																	 
SET IDENTITY_INSERT [dbo].[ResultsOfAppeals] OFF
GO
 