
SELECT ActId, [UID], ActKindId, StatusId, ResultOfAppeal, LegalDate FROM Acts 
WHERE [UID] IN ( SELECT [UID] FROM Acts GROUP BY [UID] )
ORDER BY [UID], ActId DESC

SELECT ActId, [UID],
    RN = ROW_NUMBER() OVER(PARTITION BY [UID] ORDER BY ActId DESC)
FROM Acts

-- EXEC
WITH CTE AS(
   SELECT ActId, [UID],
       RN = ROW_NUMBER() OVER(PARTITION BY [UID] ORDER BY ActId DESC)
   FROM Acts
)
SELECT * FROM CTE WHERE RN = 1
--DELETE FROM CTE WHERE RN > 1