//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace ecli
{

	public struct Declarations
	{
		public const string SchemaVersion = "https://e-justice.europa.eu/ecli";
	}

	[Serializable]
	public enum formatType
	{
        [XmlEnum(Name = "application/applefile")] application_applefile,
        [XmlEnum(Name = "application/atom+xml")] application_atom_xml,
        [XmlEnum(Name = "application/http")] application_http,
        [XmlEnum(Name = "application/mathml+xml")] application_mathm_xml,
        [XmlEnum(Name = "application/msword")] application_msword,
        [XmlEnum(Name = "application/octet-stream")] application_octet_stream,
        [XmlEnum(Name = "application/ogg")] application_ogg,
        [XmlEnum(Name = "application/pdf")] application_pdf,
        [XmlEnum(Name = "application/pgp-encrypted")] application_pgp_encrypted,
        [XmlEnum(Name = "application/pgp-keys")] application_pgp_keys,
        [XmlEnum(Name = "application/pgp-signature")] application_pgp_signature,
        [XmlEnum(Name = "application/postscript")] application_postscript,
        [XmlEnum(Name = "application/rdf+xml")] application_rdf_xml,
        [XmlEnum(Name = "application/rtf")] application_rtf,
        [XmlEnum(Name = "application/sgml")] application_sgml,
        [XmlEnum(Name = "application/smil")] application_smil,
        [XmlEnum(Name = "application/srgs")] application_srgs,
        [XmlEnum(Name = "application/srgs+xml")] application_srgs_xml,
        [XmlEnum(Name = "application/vnd.ms-excel")] application_vnd_ms_excel,
        [XmlEnum(Name = "application/vnd.ms-powerpoint")] application_vnd_ms_powerpoint,
        [XmlEnum(Name = "application/vnd.oasis.opendocument.base")] application_vnd_oasis_opendocument_base,
        [XmlEnum(Name = "application/vnd.oasis.opendocument.chart")] application_vnd_oasis_opendocument_chart,
        [XmlEnum(Name = "application/vnd.oasis.opendocument.database")] application_vnd_oasis_opendocument_database,
        [XmlEnum(Name = "application/vnd.oasis.opendocument.formula")] application_vnd_oasis_opendocument_formula,
        [XmlEnum(Name = "application/vnd.oasis.opendocument.graphics")] application_vnd_oasis_opendocument_graphics,
        [XmlEnum(Name = "application/vnd.oasis.opendocument.image")] application_vnd_oasis_opendocument_image,
        [XmlEnum(Name = "application/vnd.oasis.opendocument.presentation")] application_vnd_oasis_opendocument_presentation,
        [XmlEnum(Name = "application/vnd.oasis.opendocument.spreadsheet")] application_vnd_oasis_opendocument_spreadsheet,
        [XmlEnum(Name = "application/vnd.oasis.opendocument.text")] application_vnd_oasis_opendocument_text,
        [XmlEnum(Name = "application/vnd.oasis.opendocument.text-master")] application_vnd_oasis_opendocument_text_master,
        [XmlEnum(Name = "application/vnd.openxmlformats-officedocument.presentationml.presentation")] application_vnd_openxmlformats_officedocument_presentationml_presentation,
        [XmlEnum(Name = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")] application_vnd_openxmlformats_officedocument_spreadsheetml_sheet,
        [XmlEnum(Name = "application/vnd.openxmlformats-officedocument.wordprocessingml.document")] application_vnd_openxmlformats_officedocument_wordprocessingml_document,
        [XmlEnum(Name = "application/vnd.rn-realmedia")] application_vnd_rn_realmedia,
        [XmlEnum(Name = "application/vnd.sun.xml.base")] application_vnd_sun_xml_base,
        [XmlEnum(Name = "application/xhtml+xml")] application_xhtml_xml,
        [XmlEnum(Name = "application/xml")] application_xml,
        [XmlEnum(Name = "application/xml-dtd")] application_xml_dtd,
        [XmlEnum(Name = "application/zip")] application_zip,
        [XmlEnum(Name = "audio/basic")] audio_basic,
        [XmlEnum(Name = "audio/midi")] audio_midi,
        [XmlEnum(Name = "audio/mpeg")] audio_mpeg,
        [XmlEnum(Name = "audio/mpeg4-generic")] audio_mpeg4_generic,
        [XmlEnum(Name = "audio/x-aiff")] audio_x_aiff,
        [XmlEnum(Name = "audio/x-mpegurl")] audio_x_mpegurl,
        [XmlEnum(Name = "audio/x-pn-realaudio")] audio_x_pn_realaudio,
        [XmlEnum(Name = "audio/x-pn-realaudio-plugin")] audio_x_pn_realaudio_plugin,
        [XmlEnum(Name = "audio/x-wav")] audio_x_wav,
        [XmlEnum(Name = "image/bmp")] image_bmp,
        [XmlEnum(Name = "image/gif")] image_gif,
        [XmlEnum(Name = "image/jpeg")] image_jpeg,
        [XmlEnum(Name = "image/png")] image_png,
        [XmlEnum(Name = "image/svg+xml")] image_svg_xml,
        [XmlEnum(Name = "image/tiff")] image_tiff,
        [XmlEnum(Name = "image/vnd.wap.wbmp")] image_vnd_wap_wbmp,
        [XmlEnum(Name = "image/x-icon")] image_x_icon,
        [XmlEnum(Name = "message/http")] message_http,
        [XmlEnum(Name = "message/news")] message_news,
        [XmlEnum(Name = "text/calendar")] text_calendar,
        [XmlEnum(Name = "text/css")] text_css,
        [XmlEnum(Name = "text/directory")] text_directory,
        [XmlEnum(Name = "text/html")] text_html,
        [XmlEnum(Name = "text/plain")] text_plain,
        [XmlEnum(Name = "text/richtext")] text_richtext,
        [XmlEnum(Name = "text/rtf")] text_rtf,
        [XmlEnum(Name = "text/sgml")] text_sgml,
        [XmlEnum(Name = "text/uri-list")] text_uri_list,
        [XmlEnum(Name = "text/vnd.wap.wml")] text_vnd_wap_wml,
        [XmlEnum(Name = "text/xml")] text_xml,
        [XmlEnum(Name = "video/mpeg")] video_mpeg,
        [XmlEnum(Name = "video/quicktime")] video_quicktime,
        [XmlEnum(Name = "video/vnd.mpegurl")] video_vnd_mpegurl,
        [XmlEnum(Name = "video/x-msvideo")] video_x_msvideo,
        [XmlEnum(Name = "video/x-sgi-movie")] video_x_sgi_movie
    }

	[Serializable]
	public enum referenceType
	{
		[XmlEnum(Name="ELI")] ELI,
		[XmlEnum(Name="ECLI")] ECLI,
		[XmlEnum(Name="CELEX")] CELEX,
		[XmlEnum(Name="PATENT")] PATENT,
		[XmlEnum(Name="PATENT_APPLICATION")] PATENT_APPLICATION,
		[XmlEnum(Name="OTHER")] OTHER
	}

	[Serializable]
	public enum statusType
	{
		[XmlEnum(Name="active")] active,
		[XmlEnum(Name="deleted")] deleted
	}

	[Serializable]
	public enum relationType
	{
		[XmlEnum(Name="citing")] citing,
		[XmlEnum(Name="citedBy")] citedBy,
		[XmlEnum(Name="followedBy")] followedBy,
		[XmlEnum(Name="precededBy")] precededBy
	}

	[Serializable]
	public enum identifierTypeType
	{
		[XmlEnum(Name="nonauthorised")] nonauthorised,
		[XmlEnum(Name="summarised")] summarised
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class notEmptyTypeWithLangAndGroupCollection : System.Collections.Generic.List<ecli.notEmptyTypeWithLangAndGroup>
	{
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class languageWithGroupTypeCollection : System.Collections.Generic.List<ecli.languageWithGroupType>
	{
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class referenceWithGroupTypeCollection : System.Collections.Generic.List<ecli.ReferenceWithGroupType>
	{
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class identifierWithGroupTypeCollection : System.Collections.Generic.List<ecli.identifierWithGroupType>
	{
	}



	[XmlType(TypeName="documentType",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class documentType
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="status",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ecli.statusType __status;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __statusSpecified;
		
		[XmlIgnore]
		public ecli.statusType status
		{ 
			get { return __status; }
			set { __status = value; __statusSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.metadataType),ElementName="metadata",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ecli.metadataType __metadata;
		
		[XmlIgnore]
		public ecli.metadataType metadata
		{
			get {return __metadata;}
			set {__metadata = value;}
		}

		public documentType()
		{
		}
	}


	[XmlType(TypeName="metadataType",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class metadataType
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.identifierWithGroupType),ElementName="identifier",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public identifierWithGroupTypeCollection __identifierCollection;
		
		[XmlIgnore]
		public identifierWithGroupTypeCollection identifierCollection
		{
			get
			{
				if (__identifierCollection == null) __identifierCollection = new identifierWithGroupTypeCollection();
				return __identifierCollection;
			}
			set {__identifierCollection = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.ecliType),ElementName="isVersionOf",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ecli.ecliType __isVersionOf;
		
		[XmlIgnore]
		public ecli.ecliType isVersionOf
		{
			get {return __isVersionOf;}
			set {__isVersionOf = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.notEmptyTypeWithLangAndGroup),ElementName="creator",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public notEmptyTypeWithLangAndGroupCollection __creatorCollection;
		
		[XmlIgnore]
		public notEmptyTypeWithLangAndGroupCollection creatorCollection
		{
			get
			{
				if (__creatorCollection == null) __creatorCollection = new notEmptyTypeWithLangAndGroupCollection();
				return __creatorCollection;
			}
			set {__creatorCollection = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.notEmptyTypeWithLangAndGroup),ElementName="coverage",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public notEmptyTypeWithLangAndGroupCollection __coverageCollection;
		
		[XmlIgnore]
		public notEmptyTypeWithLangAndGroupCollection coverageCollection
		{
			get
			{
				if (__coverageCollection == null) __coverageCollection = new notEmptyTypeWithLangAndGroupCollection();
				return __coverageCollection;
			}
			set {__coverageCollection = value;}
		}

        [System.Web.Script.Serialization.ScriptIgnore]
        [XmlElement(ElementName="date",Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public Iso8601SerializableDateTimeOffset? __date;

        [System.Web.Script.Serialization.ScriptIgnore]
        [XmlIgnore]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public bool __dateSpecified { get { return __date.HasValue; } }

        [XmlIgnore]
        public Iso8601SerializableDateTimeOffset? date
        {
            get { return __date; }
            set { __date = value; }
        }



        [System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.languageWithGroupType),ElementName="language",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public languageWithGroupTypeCollection __languageCollection;
		
		[XmlIgnore]
		public languageWithGroupTypeCollection languageCollection
		{
			get
			{
				if (__languageCollection == null) __languageCollection = new languageWithGroupTypeCollection();
				return __languageCollection;
			}
			set {__languageCollection = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.notEmptyTypeWithLangAndGroup),ElementName="publisher",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public notEmptyTypeWithLangAndGroupCollection __publisherCollection;
		
		[XmlIgnore]
		public notEmptyTypeWithLangAndGroupCollection publisherCollection
		{
			get
			{
				if (__publisherCollection == null) __publisherCollection = new notEmptyTypeWithLangAndGroupCollection();
				return __publisherCollection;
			}
			set {__publisherCollection = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="accessRights",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __accessRights;
		
		[XmlIgnore]
		public string accessRights
		{ 
			get { return __accessRights; }
			set { __accessRights = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.typeType),ElementName="type",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ecli.typeType __type;
		
		[XmlIgnore]
		public ecli.typeType type
		{
			get {return __type;}
			set {__type = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.notEmptyTypeWithLangAndGroup),ElementName="title",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public notEmptyTypeWithLangAndGroupCollection __titleCollection;
		
		[XmlIgnore]
		public notEmptyTypeWithLangAndGroupCollection titleCollection
		{
			get
			{
				if (__titleCollection == null) __titleCollection = new notEmptyTypeWithLangAndGroupCollection();
				return __titleCollection;
			}
			set {__titleCollection = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.notEmptyTypeWithLangAndGroup),ElementName="subject",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public notEmptyTypeWithLangAndGroupCollection __subjectCollection;
		
		[XmlIgnore]
		public notEmptyTypeWithLangAndGroupCollection subjectCollection
		{
			get
			{
				if (__subjectCollection == null) __subjectCollection = new notEmptyTypeWithLangAndGroupCollection();
				return __subjectCollection;
			}
			set {__subjectCollection = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.notEmptyTypeWithLangAndGroup),ElementName="abstract",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public notEmptyTypeWithLangAndGroupCollection __abstractCollection;
		
		[XmlIgnore]
		public notEmptyTypeWithLangAndGroupCollection abstractCollection
		{
			get
			{
				if (__abstractCollection == null) __abstractCollection = new notEmptyTypeWithLangAndGroupCollection();
				return __abstractCollection;
			}
			set {__abstractCollection = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.notEmptyTypeWithLangAndGroup),ElementName="description",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public notEmptyTypeWithLangAndGroupCollection __descriptionCollection;
		
		[XmlIgnore]
		public notEmptyTypeWithLangAndGroupCollection descriptionCollection
		{
			get
			{
				if (__descriptionCollection == null) __descriptionCollection = new notEmptyTypeWithLangAndGroupCollection();
				return __descriptionCollection;
			}
			set {__descriptionCollection = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.notEmptyTypeWithLangAndGroup),ElementName="contributor",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public notEmptyTypeWithLangAndGroupCollection __contributorCollection;
		
		[XmlIgnore]
		public notEmptyTypeWithLangAndGroupCollection contributorCollection
		{
			get
			{
				if (__contributorCollection == null) __contributorCollection = new notEmptyTypeWithLangAndGroupCollection();
				return __contributorCollection;
			}
			set {__contributorCollection = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="issued",Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Iso8601SerializableDateTimeOffset? __issued;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __issuedSpecified { get { return __issued.HasValue; } }
		
		[XmlIgnore]
		public Iso8601SerializableDateTimeOffset? issued
		{ 
			get { return __issued; }
			set { __issued = value; }
		}
		


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.ReferenceWithGroupType),ElementName="reference",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public referenceWithGroupTypeCollection __referenceCollection;
		
		[XmlIgnore]
		public referenceWithGroupTypeCollection referenceCollection
		{
			get
			{
				if (__referenceCollection == null) __referenceCollection = new referenceWithGroupTypeCollection();
				return __referenceCollection;
			}
			set {__referenceCollection = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ecli.ecliType),ElementName="isReplacedBy",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ecli.ecliType __isReplacedBy;
		
		[XmlIgnore]
		public ecli.ecliType isReplacedBy
		{
			get {return __isReplacedBy;}
			set {__isReplacedBy = value;}
		}

		public metadataType()
		{
		}
	}


	[XmlType(TypeName="ecliType",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ecliType
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="value",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __value;
		
		[XmlIgnore]
		public string @value
		{ 
			get { return __value; }
			set { __value = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="country",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ecli_types.countryType __country;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __countrySpecified;
		
		[XmlIgnore]
		public ecli_types.countryType country
		{ 
			get { return __country; }
			set { __country = value; __countrySpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="court",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __court;
		
		[XmlIgnore]
		public string court
		{ 
			get { return __court; }
			set { __court = value; }
		}

		public ecliType()
		{
		}
	}


	[XmlType(TypeName="notEmptyWithGroupType",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class notEmptyWithGroupType
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="group",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __group;
		
		[XmlIgnore]
		public string group
		{ 
			get { return __group; }
			set { __group = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlText(DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __MixedValue;
		
		[XmlIgnore]
		public string MixedValue
		{ 
			get { return __MixedValue; }
			set { __MixedValue = value; }
		}

		public notEmptyWithGroupType()
		{
		}
	}


	[XmlType(TypeName="notEmptyTypeWithLang",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class notEmptyTypeWithLang
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="lang")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ecli_types.languageType __lang;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __langSpecified;
		
		[XmlIgnore]
		public ecli_types.languageType lang
		{ 
			get { return __lang; }
			set { __lang = value; __langSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlText(DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __MixedValue;
		
		[XmlIgnore]
		public string MixedValue
		{ 
			get { return __MixedValue; }
			set { __MixedValue = value; }
		}

		public notEmptyTypeWithLang()
		{
		}
	}


	[XmlType(TypeName="notEmptyTypeWithLangAndGroup",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class notEmptyTypeWithLangAndGroup : ecli.notEmptyTypeWithLang
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="group",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __group;
		
		[XmlIgnore]
		public string group
		{ 
			get { return __group; }
			set { __group = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlText(DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public new string __MixedValue;
		
		[XmlIgnore]
        public new string MixedValue
		{ 
			get { return __MixedValue; }
			set { __MixedValue = value; }
		}

		public notEmptyTypeWithLangAndGroup() : base()
		{
		}
	}


	[XmlType(TypeName="identifierType",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class identifierType
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="lang")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ecli_types.languageType __lang;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __langSpecified;
		
		[XmlIgnore]
		public ecli_types.languageType lang
		{ 
			get { return __lang; }
			set { __lang = value; __langSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="format")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ecli_types.formatType __format;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __formatSpecified;
		
		[XmlIgnore]
		public ecli_types.formatType format
		{ 
			get { return __format; }
			set { __format = value; __formatSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="type")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ecli_types.identifierTypeType __type;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __typeSpecified;
		
		[XmlIgnore]
		public ecli_types.identifierTypeType type
		{ 
			get { return __type; }
			set { __type = value; __typeSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlText(DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __MixedValue;
		
		[XmlIgnore]
		public string MixedValue
		{ 
			get { return __MixedValue; }
			set { __MixedValue = value; }
		}

		public identifierType()
		{
		}
	}


	[XmlType(TypeName="identifierWithGroupType",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class identifierWithGroupType : ecli.identifierType
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="group",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __group;
		
		[XmlIgnore]
		public string group
		{ 
			get { return __group; }
			set { __group = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlText(DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
        public new string __MixedValue;
		
		[XmlIgnore]
        public new string MixedValue
		{ 
			get { return __MixedValue; }
			set { __MixedValue = value; }
		}

		public identifierWithGroupType() : base()
		{
		}
	}


	[XmlType(TypeName="languageType2",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class languageType
    {

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="languageType")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __languageType;
		
		[XmlIgnore]
		public string languageTypeType
		{ 
			get { return __languageType; }
			set { __languageType = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlText(DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __MixedValue;
		
		[XmlIgnore]
		public string MixedValue
		{ 
			get { return __MixedValue; }
			set { __MixedValue = value; }
		}

		public languageType()
		{
		}
	}


	[XmlType(TypeName="languageWithGroupType",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class languageWithGroupType : ecli.languageType
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="group",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __group;
		
		[XmlIgnore]
		public string group
		{ 
			get { return __group; }
			set { __group = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlText(DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
        public new string __MixedValue;
		
		[XmlIgnore]
        public new string MixedValue
		{ 
			get { return __MixedValue; }
			set { __MixedValue = value; }
		}

		public languageWithGroupType() : base()
		{
		}
	}


	[XmlType(TypeName="typeType",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class typeType
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="lang")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ecli_types.languageType __lang;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __langSpecified;
		
		[XmlIgnore]
		public ecli_types.languageType lang
		{ 
			get { return __lang; }
			set { __lang = value; __langSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlText(DataType= "string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __MixedValue;
		
		[XmlIgnore]
		public string MixedValue
		{ 
			get { return __MixedValue; }
			set { __MixedValue = value; }
		}

		public typeType()
		{
		}
	}


	[XmlType(TypeName="referenceType2",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ReferenceType
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="type")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ecli_types.referenceType __type;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __typeSpecified;
		
		[XmlIgnore]
		public ecli_types.referenceType type
		{ 
			get { return __type; }
			set { __type = value; __typeSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="relation")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ecli_types.relationType __relation;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __relationSpecified;
		
		[XmlIgnore]
		public ecli_types.relationType relation
		{ 
			get { return __relation; }
			set { __relation = value; __relationSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="lang")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ecli_types.languageType __lang;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __langSpecified;
		
		[XmlIgnore]
		public ecli_types.languageType lang
		{ 
			get { return __lang; }
			set { __lang = value; __langSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlText(DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __MixedValue;
		
		[XmlIgnore]
		public string MixedValue
		{ 
			get { return __MixedValue; }
			set { __MixedValue = value; }
		}

		public ReferenceType()
		{
		}
	}


	[XmlType(TypeName="referenceWithGroupType",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ReferenceWithGroupType : ecli.ReferenceType
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="group",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __group;
		
		[XmlIgnore]
		public string group
		{ 
			get { return __group; }
			set { __group = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlText(DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
        public new string __MixedValue;
		
		[XmlIgnore]
        public new string MixedValue
		{ 
			get { return __MixedValue; }
			set { __MixedValue = value; }
		}

		public ReferenceWithGroupType() : base()
		{
		}
	}


	[XmlRoot(ElementName="document",Namespace=Declarations.SchemaVersion,IsNullable=false),Serializable]
	public partial class document : ecli.documentType
	{

		public document() : base()
		{
		}
	}
}
