//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace sitemap
{

	public struct Declarations
	{
        public const string SchemaVersion = "http://www.sitemaps.org/schemas/sitemap/0.9";
    }

	[Serializable]
	public enum tChangeFreq
	{
		[XmlEnum(Name="always")] always,
		[XmlEnum(Name="hourly")] hourly,
		[XmlEnum(Name="daily")] daily,
		[XmlEnum(Name="weekly")] weekly,
		[XmlEnum(Name="monthly")] monthly,
		[XmlEnum(Name="yearly")] yearly,
		[XmlEnum(Name="never")] never
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class tUrlCollection : System.Collections.Generic.List<sitemap.tUrl>
	{
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class tSitemapCollection : System.Collections.Generic.List<sitemap.tSitemap>
	{
	}



	[XmlType(TypeName="tSitemap",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class tSitemap
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="loc",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="anyURI",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __loc;
		
		[XmlIgnore]
		public string loc
		{ 
			get { return __loc; }
			set { __loc = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="lastmod",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __lastmod;
		
		[XmlIgnore]
		public string lastmod
		{ 
			get { return __lastmod; }
			set { __lastmod = value; }
		}

		public tSitemap()
		{
		}
	}


	[XmlType(TypeName="tUrl",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class tUrl
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="loc",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="anyURI",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __loc;
		
		[XmlIgnore]
		public string loc
		{ 
			get { return __loc; }
			set { __loc = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="lastmod",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __lastmod;
		
		[XmlIgnore]
		public string lastmod
		{ 
			get { return __lastmod; }
			set { __lastmod = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="changefreq",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public sitemap.tChangeFreq __changefreq;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __changefreqSpecified;
		
		[XmlIgnore]
		public sitemap.tChangeFreq changefreq
		{ 
			get { return __changefreq; }
			set { __changefreq = value; __changefreqSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="priority",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="decimal",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public decimal __priority;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __prioritySpecified;
		
		[XmlIgnore]
		public decimal priority
		{ 
			get { return __priority; }
			set { __priority = value; __prioritySpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAnyElement()]
		public System.Xml.XmlElement[] Any;

		public tUrl()
		{
		}
	}


	[XmlRoot(ElementName="sitemapindex",Namespace=Declarations.SchemaVersion,IsNullable=false),Serializable]
	public partial class sitemapindex
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(sitemap.tSitemap),ElementName="sitemap",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public tSitemapCollection __sitemapCollection;
		
		[XmlIgnore]
		public tSitemapCollection sitemapCollection
		{
			get
			{
				if (__sitemapCollection == null) __sitemapCollection = new tSitemapCollection();
				return __sitemapCollection;
			}
			set {__sitemapCollection = value;}
		}

		public sitemapindex()
		{
		}
	}


	[XmlRoot(ElementName="urlset",Namespace=Declarations.SchemaVersion,IsNullable=false),Serializable]
	public partial class urlset
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(sitemap.tUrl),ElementName="url",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public tUrlCollection __urlCollection;
		
		[XmlIgnore]
		public tUrlCollection urlCollection
		{
			get
			{
				if (__urlCollection == null) __urlCollection = new tUrlCollection();
				return __urlCollection;
			}
			set {__urlCollection = value;}
		}

		public urlset()
		{
		}
	}
}
