// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Legalacts.Web.Controllers
{
    public partial class AdminController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdminController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditActKinds()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditActKinds);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditCaseKinds()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditCaseKinds);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Acts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Acts);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminController Actions { get { return MVC.Admin; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string admin = "admin";
            public readonly string LogOn = "LogOn";
            public readonly string LogOff = "LogOff";
            public readonly string ChangePassword = "ChangePassword";
            public readonly string Search = "Search";
            public readonly string Nomenclatures = "Nomenclatures";
            public readonly string EditActKinds = "EditActKinds";
            public readonly string EditCaseKinds = "EditCaseKinds";
            public readonly string Acts = "Acts";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string admin = "admin";
            public const string LogOn = "LogOn";
            public const string LogOff = "LogOff";
            public const string ChangePassword = "ChangePassword";
            public const string Search = "Search";
            public const string Nomenclatures = "Nomenclatures";
            public const string EditActKinds = "EditActKinds";
            public const string EditCaseKinds = "EditCaseKinds";
            public const string Acts = "Acts";
        }


        static readonly ActionParamsClass_LogOn s_params_LogOn = new ActionParamsClass_LogOn();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LogOn LogOnParams { get { return s_params_LogOn; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LogOn
        {
            public readonly string vm = "vm";
            public readonly string ReturnUrl = "ReturnUrl";
            public readonly string captchaValid = "captchaValid";
        }
        static readonly ActionParamsClass_ChangePassword s_params_ChangePassword = new ActionParamsClass_ChangePassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangePassword ChangePasswordParams { get { return s_params_ChangePassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangePassword
        {
            public readonly string vm = "vm";
        }
        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search
        {
            public readonly string courtId = "courtId";
            public readonly string actionLogTypeId = "actionLogTypeId";
            public readonly string dateFrom = "dateFrom";
            public readonly string dateTo = "dateTo";
            public readonly string showResults = "showResults";
            public readonly string page = "page";
            public readonly string vm = "vm";
        }
        static readonly ActionParamsClass_EditActKinds s_params_EditActKinds = new ActionParamsClass_EditActKinds();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditActKinds EditActKindsParams { get { return s_params_EditActKinds; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditActKinds
        {
            public readonly string vm = "vm";
        }
        static readonly ActionParamsClass_EditCaseKinds s_params_EditCaseKinds = new ActionParamsClass_EditCaseKinds();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditCaseKinds EditCaseKindsParams { get { return s_params_EditCaseKinds; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditCaseKinds
        {
            public readonly string vm = "vm";
        }
        static readonly ActionParamsClass_Acts s_params_Acts = new ActionParamsClass_Acts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Acts ActsParams { get { return s_params_Acts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Acts
        {
            public readonly string year = "year";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Acts = "Acts";
                public readonly string ChangePassword = "ChangePassword";
                public readonly string LogOn = "LogOn";
                public readonly string Nomenclatures = "Nomenclatures";
                public readonly string Search = "Search";
            }
            public readonly string Acts = "~/Views/Admin/Acts.cshtml";
            public readonly string ChangePassword = "~/Views/Admin/ChangePassword.cshtml";
            public readonly string LogOn = "~/Views/Admin/LogOn.cshtml";
            public readonly string Nomenclatures = "~/Views/Admin/Nomenclatures.cshtml";
            public readonly string Search = "~/Views/Admin/Search.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AdminController : Legalacts.Web.Controllers.AdminController
    {
        public T4MVC_AdminController() : base(Dummy.Instance) { }

        [NonAction]
        partial void adminOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult admin()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.admin);
            adminOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LogOnOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LogOn()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogOn);
            LogOnOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LogOnOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Legalacts.Web.Models.LogonVM vm, string ReturnUrl, bool? captchaValid);

        [NonAction]
        public override System.Web.Mvc.ActionResult LogOn(Legalacts.Web.Models.LogonVM vm, string ReturnUrl, bool? captchaValid)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogOn);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vm", vm);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ReturnUrl", ReturnUrl);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "captchaValid", captchaValid);
            LogOnOverride(callInfo, vm, ReturnUrl, captchaValid);
            return callInfo;
        }

        [NonAction]
        partial void LogOffOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LogOff()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogOff);
            LogOffOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ChangePasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ChangePassword()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangePassword);
            ChangePasswordOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ChangePasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Legalacts.Web.Models.ChangePasswordVM vm);

        [NonAction]
        public override System.Web.Mvc.ActionResult ChangePassword(Legalacts.Web.Models.ChangePasswordVM vm)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangePassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vm", vm);
            ChangePasswordOverride(callInfo, vm);
            return callInfo;
        }

        [NonAction]
        partial void SearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string courtId, string actionLogTypeId, string dateFrom, string dateTo, bool showResults, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Search(string courtId, string actionLogTypeId, string dateFrom, string dateTo, bool showResults, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "courtId", courtId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actionLogTypeId", actionLogTypeId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dateFrom", dateFrom);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dateTo", dateTo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showResults", showResults);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            SearchOverride(callInfo, courtId, actionLogTypeId, dateFrom, dateTo, showResults, page);
            return callInfo;
        }

        [NonAction]
        partial void SearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Legalacts.Web.Models.SearchLogVM vm);

        [NonAction]
        public override System.Web.Mvc.ActionResult Search(Legalacts.Web.Models.SearchLogVM vm)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vm", vm);
            SearchOverride(callInfo, vm);
            return callInfo;
        }

        [NonAction]
        partial void NomenclaturesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Nomenclatures()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Nomenclatures);
            NomenclaturesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EditActKindsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Legalacts.Web.Models.NomenclaturesVM vm);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditActKinds(Legalacts.Web.Models.NomenclaturesVM vm)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditActKinds);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vm", vm);
            EditActKindsOverride(callInfo, vm);
            return callInfo;
        }

        [NonAction]
        partial void EditCaseKindsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Legalacts.Web.Models.NomenclaturesVM vm);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditCaseKinds(Legalacts.Web.Models.NomenclaturesVM vm)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditCaseKinds);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vm", vm);
            EditCaseKindsOverride(callInfo, vm);
            return callInfo;
        }

        [NonAction]
        partial void ActsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? year);

        [NonAction]
        public override System.Web.Mvc.ActionResult Acts(int? year)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Acts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "year", year);
            ActsOverride(callInfo, year);
            return callInfo;
        }

        [NonAction]
        partial void ActsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string year);

        [NonAction]
        public override System.Web.Mvc.ActionResult Acts(string year)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Acts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "year", year);
            ActsOverride(callInfo, year);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
