// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Legalacts.Web.Controllers
{
    public partial class SearchController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SearchController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SearchController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UidDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UidDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Details()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DetailsByEcli()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetailsByEcli);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetActContentByEcli()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetActContentByEcli);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetMotiveContentByEcli()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetMotiveContentByEcli);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileResult GetActContentByActId()
        {
            return new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.GetActContentByActId);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileResult GetMotiveContentByActId()
        {
            return new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.GetMotiveContentByActId);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SearchController Actions { get { return MVC.Search; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Search";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Search";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Search = "Search";
            public readonly string UidDetails = "UidDetails";
            public readonly string Details = "Details";
            public readonly string DetailsByEcli = "DetailsByEcli";
            public readonly string GetActContentByEcli = "GetActContentByEcli";
            public readonly string GetMotiveContentByEcli = "GetMotiveContentByEcli";
            public readonly string GetActContentByActId = "GetActContentByActId";
            public readonly string GetMotiveContentByActId = "GetMotiveContentByActId";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Search = "Search";
            public const string UidDetails = "UidDetails";
            public const string Details = "Details";
            public const string DetailsByEcli = "DetailsByEcli";
            public const string GetActContentByEcli = "GetActContentByEcli";
            public const string GetMotiveContentByEcli = "GetMotiveContentByEcli";
            public const string GetActContentByActId = "GetActContentByActId";
            public const string GetMotiveContentByActId = "GetMotiveContentByActId";
        }


        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search
        {
            public readonly string courtId = "courtId";
            public readonly string caseKindId = "caseKindId";
            public readonly string caseNumber = "caseNumber";
            public readonly string caseYear = "caseYear";
            public readonly string judge = "judge";
            public readonly string actKindId = "actKindId";
            public readonly string statusId = "statusId";
            public readonly string actNumber = "actNumber";
            public readonly string actYear = "actYear";
            public readonly string dateFrom = "dateFrom";
            public readonly string dateTo = "dateTo";
            public readonly string ecli = "ecli";
            public readonly string keyWord = "keyWord";
            public readonly string showConnected = "showConnected";
            public readonly string isLuceneInUse = "isLuceneInUse";
            public readonly string showResults = "showResults";
            public readonly string isAdvanced = "isAdvanced";
            public readonly string page = "page";
            public readonly string vm = "vm";
            public readonly string captchaValid = "captchaValid";
        }
        static readonly ActionParamsClass_UidDetails s_params_UidDetails = new ActionParamsClass_UidDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UidDetails UidDetailsParams { get { return s_params_UidDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UidDetails
        {
            public readonly string uid = "uid";
        }
        static readonly ActionParamsClass_Details s_params_Details = new ActionParamsClass_Details();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Details DetailsParams { get { return s_params_Details; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Details
        {
            public readonly string actId = "actId";
        }
        static readonly ActionParamsClass_DetailsByEcli s_params_DetailsByEcli = new ActionParamsClass_DetailsByEcli();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DetailsByEcli DetailsByEcliParams { get { return s_params_DetailsByEcli; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DetailsByEcli
        {
            public readonly string ecli = "ecli";
        }
        static readonly ActionParamsClass_GetActContentByEcli s_params_GetActContentByEcli = new ActionParamsClass_GetActContentByEcli();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetActContentByEcli GetActContentByEcliParams { get { return s_params_GetActContentByEcli; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetActContentByEcli
        {
            public readonly string ecli = "ecli";
        }
        static readonly ActionParamsClass_GetMotiveContentByEcli s_params_GetMotiveContentByEcli = new ActionParamsClass_GetMotiveContentByEcli();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetMotiveContentByEcli GetMotiveContentByEcliParams { get { return s_params_GetMotiveContentByEcli; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetMotiveContentByEcli
        {
            public readonly string ecli = "ecli";
        }
        static readonly ActionParamsClass_GetActContentByActId s_params_GetActContentByActId = new ActionParamsClass_GetActContentByActId();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetActContentByActId GetActContentByActIdParams { get { return s_params_GetActContentByActId; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetActContentByActId
        {
            public readonly string actId = "actId";
        }
        static readonly ActionParamsClass_GetMotiveContentByActId s_params_GetMotiveContentByActId = new ActionParamsClass_GetMotiveContentByActId();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetMotiveContentByActId GetMotiveContentByActIdParams { get { return s_params_GetMotiveContentByActId; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetMotiveContentByActId
        {
            public readonly string actId = "actId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Details = "Details";
                public readonly string Search = "Search";
            }
            public readonly string Details = "~/Views/Search/Details.cshtml";
            public readonly string Search = "~/Views/Search/Search.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SearchController : Legalacts.Web.Controllers.SearchController
    {
        public T4MVC_SearchController() : base(Dummy.Instance) { }

        [NonAction]
        partial void SearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string courtId, string caseKindId, string caseNumber, string caseYear, string judge, string actKindId, string statusId, string actNumber, string actYear, string dateFrom, string dateTo, string ecli, string keyWord, bool showConnected, bool isLuceneInUse, bool showResults, bool isAdvanced, string page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Search(string courtId, string caseKindId, string caseNumber, string caseYear, string judge, string actKindId, string statusId, string actNumber, string actYear, string dateFrom, string dateTo, string ecli, string keyWord, bool showConnected, bool isLuceneInUse, bool showResults, bool isAdvanced, string page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "courtId", courtId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "caseKindId", caseKindId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "caseNumber", caseNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "caseYear", caseYear);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "judge", judge);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actKindId", actKindId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "statusId", statusId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actNumber", actNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actYear", actYear);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dateFrom", dateFrom);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dateTo", dateTo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ecli", ecli);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "keyWord", keyWord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showConnected", showConnected);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isLuceneInUse", isLuceneInUse);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showResults", showResults);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isAdvanced", isAdvanced);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            SearchOverride(callInfo, courtId, caseKindId, caseNumber, caseYear, judge, actKindId, statusId, actNumber, actYear, dateFrom, dateTo, ecli, keyWord, showConnected, isLuceneInUse, showResults, isAdvanced, page);
            return callInfo;
        }

        [NonAction]
        partial void SearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Legalacts.Web.Models.SearchVM vm, bool? captchaValid);

        [NonAction]
        public override System.Web.Mvc.ActionResult Search(Legalacts.Web.Models.SearchVM vm, bool? captchaValid)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vm", vm);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "captchaValid", captchaValid);
            SearchOverride(callInfo, vm, captchaValid);
            return callInfo;
        }

        [NonAction]
        partial void UidDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string uid);

        [NonAction]
        public override System.Web.Mvc.ActionResult UidDetails(string uid)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UidDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "uid", uid);
            UidDetailsOverride(callInfo, uid);
            return callInfo;
        }

        [NonAction]
        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string actId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Details(string actId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actId", actId);
            DetailsOverride(callInfo, actId);
            return callInfo;
        }

        [NonAction]
        partial void DetailsByEcliOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string ecli);

        [NonAction]
        public override System.Web.Mvc.ActionResult DetailsByEcli(string ecli)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetailsByEcli);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ecli", ecli);
            DetailsByEcliOverride(callInfo, ecli);
            return callInfo;
        }

        [NonAction]
        partial void GetActContentByEcliOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string ecli);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetActContentByEcli(string ecli)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetActContentByEcli);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ecli", ecli);
            GetActContentByEcliOverride(callInfo, ecli);
            return callInfo;
        }

        [NonAction]
        partial void GetMotiveContentByEcliOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string ecli);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetMotiveContentByEcli(string ecli)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetMotiveContentByEcli);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ecli", ecli);
            GetMotiveContentByEcliOverride(callInfo, ecli);
            return callInfo;
        }

        [NonAction]
        partial void GetActContentByActIdOverride(T4MVC_System_Web_Mvc_FileResult callInfo, string actId);

        [NonAction]
        public override System.Web.Mvc.FileResult GetActContentByActId(string actId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.GetActContentByActId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actId", actId);
            GetActContentByActIdOverride(callInfo, actId);
            return callInfo;
        }

        [NonAction]
        partial void GetMotiveContentByActIdOverride(T4MVC_System_Web_Mvc_FileResult callInfo, string actId);

        [NonAction]
        public override System.Web.Mvc.FileResult GetMotiveContentByActId(string actId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.GetMotiveContentByActId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "actId", actId);
            GetMotiveContentByActIdOverride(callInfo, actId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
