// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static Legalacts.Web.Controllers.AccountController Account = new Legalacts.Web.Controllers.T4MVC_AccountController();
    public static Legalacts.Web.Controllers.AdminController Admin = new Legalacts.Web.Controllers.T4MVC_AdminController();
    public static Legalacts.Web.Controllers.HomeController Home = new Legalacts.Web.Controllers.T4MVC_HomeController();
    public static Legalacts.Web.Controllers.SearchController Search = new Legalacts.Web.Controllers.T4MVC_SearchController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

#pragma warning disable 0436
namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}
#pragma warning restore 0436

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_FileResult : System.Web.Mvc.FileResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_FileResult(string area, string controller, string action, string protocol = null): base(" ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    protected override void WriteFile(System.Web.HttpResponseBase response) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        public const string UrlPath = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        public static readonly string canvasloader_min_0_9_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/canvasloader-min-0.9.1.min.js") ? Url("canvasloader-min-0.9.1.min.js") : Url("canvasloader-min-0.9.1.js");
        public static readonly string jquery_1_11_1_min_js = Url("jquery-1.11.1.min.js");
        public static readonly string jquery_ui_min_js = Url("jquery-ui.min.js");
        public static readonly string jquery_easing_1_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.easing.1.3.min.js") ? Url("jquery.easing.1.3.min.js") : Url("jquery.easing.1.3.js");
        public static readonly string scripts_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/scripts.min.js") ? Url("scripts.min.js") : Url("scripts.js");
        public static readonly string select2_min_js = Url("select2.min.js");
        public static readonly string select2_locale_bg_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/select2_locale_bg.min.js") ? Url("select2_locale_bg.min.js") : Url("select2_locale_bg.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        public const string UrlPath = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class img {
            public const string UrlPath = "~/Content/img";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string alert_png = Url("alert.png");
            public static readonly string back_png = Url("back.png");
            public static readonly string bg_home_jpg = Url("bg-home.jpg");
            public static readonly string bg_inner_jpg = Url("bg-inner.jpg");
            public static readonly string checkbox_gif = Url("checkbox.gif");
            public static readonly string footer_logos_gif = Url("footer-logos.gif");
            public static readonly string gerb_png = Url("gerb.png");
            public static readonly string ico_date_gif = Url("ico_date.gif");
            public static readonly string ico_info_png = Url("ico_info.png");
            public static readonly string ico_info_blue_png = Url("ico_info_blue.png");
            public static readonly string row_arrow_left_gif = Url("row-arrow-left.gif");
            public static readonly string row_arrow_left_png = Url("row-arrow-left.png");
            public static readonly string row_arrow_right_gif = Url("row-arrow-right.gif");
            public static readonly string row_arrow_right_png = Url("row-arrow-right.png");
            public static readonly string scroll_top_png = Url("scroll-top.png");
            public static readonly string search_png = Url("search.png");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class styles {
            public const string UrlPath = "~/Content/styles";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class images {
                public const string UrlPath = "~/Content/styles/images";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string animated_overlay_gif = Url("animated-overlay.gif");
                public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                public static readonly string ui_bg_flat_100_897a83_40x100_png = Url("ui-bg_flat_100_897a83_40x100.png");
                public static readonly string ui_bg_flat_100_FFF_40x100_png = Url("ui-bg_flat_100_FFF_40x100.png");
                public static readonly string ui_bg_flat_100_FFFFFF_40x100_png = Url("ui-bg_flat_100_FFFFFF_40x100.png");
                public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                public static readonly string ui_icons_000000_256x240_png = Url("ui-icons_000000_256x240.png");
                public static readonly string ui_icons_443c41_256x240_png = Url("ui-icons_443c41_256x240.png");
                public static readonly string ui_icons_897a83_256x240_png = Url("ui-icons_897a83_256x240.png");
                public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                public static readonly string ui_icons_FFFFFF_256x240_png = Url("ui-icons_FFFFFF_256x240.png");
            }
        
            public static readonly string jquery_ui_min_css = Url("jquery-ui.min.css");
            public static readonly string select2_spinner_gif = Url("select2-spinner.gif");
            public static readonly string select2_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/select2.min.css") ? Url("select2.min.css") : Url("select2.css");
            public static readonly string select2_png = Url("select2.png");
            public static readonly string select2x2_png = Url("select2x2.png");
            public static readonly string style_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/style.min.css") ? Url("style.min.css") : Url("style.css");
        }
    
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static class Assets
            {
                public static readonly string _references_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/_references.js"); 
                public static readonly string bootstrap_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap.min.js"); 
                public static readonly string canvasloader_min_0_9_1_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/canvasloader-min-0.9.1.js"); 
                public static readonly string jquery_1_11_1_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-1.11.1.min.js"); 
                public static readonly string jquery_ui_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-ui.min.js"); 
                public static readonly string jquery_easing_1_3_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.easing.1.3.js"); 
                public static readonly string scripts_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/scripts.js"); 
                public static readonly string select2_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/select2.min.js"); 
                public static readonly string select2_locale_bg_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/select2_locale_bg.js"); 
            }
        }
        public static partial class Content 
        {
            public static partial class img 
            {
                public static class Assets
                {
                }
            }
            public static partial class styles 
            {
                public static partial class images 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                    public static readonly string bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/styles/bootstrap.min.css");
                    public static readonly string jquery_ui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/styles/jquery-ui.min.css");
                    public static readonly string select2_css = T4MVCHelpers.ProcessAssetPath("~/Content/styles/select2.css");
                    public static readonly string style_css = T4MVCHelpers.ProcessAssetPath("~/Content/styles/style.css");
                }
            }
            public static class Assets
            {
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    private static string ProcessAssetPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and should retain this prefix
        return virtualPath;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;
    public static Func<string, string> ProcessAssetPath = ProcessAssetPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


